config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :products
  
  root 'static_pages#home'

  get '/about', to: 'static_pages#about' 

  get '/contact', to: 'static_pages#contact'
  
  get '/products', to: 'products#products'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  #app/models/product.rb
  belongs_to :category
  
  has_attached_file :image
    #This validates the type of file uploaded. According to this, only images are allowed.
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  do_not_validate_attachment_file_type :image
  validates_attachment :image, presence: true,
  content_type: { content_type: "image/jpeg" },
  size: { in: 0..3000.kilobytes }
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

 
    
    #app/controllers/products_controller.rb
def new 
  @product = Product.new 
  @categories = Category.all.map{|c| [ c.name, c.id ] }
end
    


  # GET /products/1/edit
  def edit
   @categories = Category.all.map{|c| [ c.name, c.id ] } 
  end

  # POST /products
  # POST /products.json
  
  def create 

    @product = Product.new(product_params)
  @product.category_id = params[:category_id] 
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product.category_id = params[:category_id]
    @categories = Category.all.map{|c| [ c.name, c.id ] }
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :category, :caloriesPerServing, :glutenFree, :containsNuts, :description, :image)
    end
end

app/views/layouts/_footer.html.erb
<footer class="foot">



<%= link_to 'New Product', new_product_path, :class =>"button", :role=>"button" %>

<%= link_to 'New Category', new_category_path, :class => "button", :role=>"button" %>




</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=yield(:title) %> | Bakery</title>
    <%= csrf_meta_tags %>
    <h1>Welcome to the Bakery</h1>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <header class=nav>
        <li><a <%= link_to 'Home', root_path %>> Home </a></li>
        <li><a <%= link_to 'About', about_path %>> About </a></li>
        <li><a <%= link_to 'Contact', contact_path %>> Contact </a></li>
        <li><a <%= link_to 'Products', products_path %>> Our Cakes </a></li>
  </header>
  <h1><center>We make your sweet dreams come true...</center></h1>
  
   <div class="container"> 
    <%= yield %> 
    </div> 
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, html: { multipart: true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@product.errors.count, "error")} prohibited this photo from being saved:" %>
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <% f.label :image_content_type %>
    <% f.text_field :image_content_type, id: :product_image_content_type %>
  </div>
  <table style="width: 60%;">
  <tr>
    <div class="form-group">
      <td class="labl">Image</td>
      <td class="fullwid"><%= f.file_field :image, class: 'form-control' %></td>
    </div>
  </tr>
  <tr>
    <div class="form-group">
      <td class="labl">Name</td>
      <td class="fullwid"><%= f.text_field :name, id: :product_name %></td>
    </div>
  </tr>
  <tr>
    <div class="form-group">
      <td class="labl">Price</td>
      <td class="fullwid"><%= f.text_field :price, id: :product_price %></td>
    </div>
  </td>
  <!--  select here -->
  <tr>
    <div class="form-group">
      <td class="labl"><% f.label :category_id %></td>
      <td class="fullwid"><%= select_tag(:category_id, options_for_select(@categories), :prompt => 'Select one!') %></td>
    </div>
  </tr>
  <tr>
  <div class="form-group">
    <td class="labl">Calorie Per Serving</td>
    <td class="fullwid"><%= f.number_field :caloriesPerServing, id: :product_caloriesPerServing %></td>
  </div>
  </tr>
  <tr>
    <div class="form-group">
      <td class="labl">Gluten Free</td>
      <td class="fullwid"><%= f.check_box :glutenFree, id: :product_glutenFree %></td>
    </div>
  </tr>
  <tr>
    <div class="form-group">
      <td class="label">Contains Nuts</td>
      <td class="fullwid"><%= f.check_box :containsNuts, id: :product_containsNuts %></td>
    </div>
  </tr>
  <tr>
    <div class="form-group">
      <td class="labl">Description</td>
      <td class="fullwid"><%= f.text_area :description, id: :product_description %></td>
    </div>
  </tr>
  <tr>
  <div class="form-group">
        <td><%= f.submit 'Update Product', class: 'btn btn-default' %></td>
  </div>
  </tr>
<% end %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row products">
<h2>See full range of our delicious Cakes!</h2>

    <% @products.each do |product| %>
    
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 text-center">
        <%= link_to (image_tag product.image, :class=>"img-responsive"), product %>
        <h2><%= product.name %></h2>
        <h4>Price: <%= product.price %></h4>
        <p>Calories per Serving: <%= product.caloriesPerServing %></p>
        <p>Gluten Free: 
        <%  if product.glutenFree? %>Yes
        <% else %>No 
        <% end %></p>
        <p>Product contains Nuts: 
        <% if product.containsNuts? %>Yes
        <% else %>No 
        <% end %>
        </p>
        <p><%= product.description %></p>
     

       <br>
       <br>
       <br>
        
        
        <p><%= link_to Category.find(product.category_id).name, category_path(product.category_id) %></p>
        
        <p><%= link_to 'Show', product, :class=>"btn btn-primary" %>
        <%= link_to 'Edit', edit_product_path(product) %>
       <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
      
      </div>
   <% end %>
     </div>
    
<%= link_to 'New Product', new_product_path, :class=>"btn btn-primary" %>  